### ISSUE TITLE
Need information 

### ISSUE THREAD

**Issue by bikee1235** [davidahouse/xcodebuild-to-json#1]
Can you please add Detail README file

**Comment by davidahouse** [comment]
@bikee1235 Yes, gladly! I just pushed this up yesterday and haven't started to use it yet, but I'll add some info to the readme soon. Are you looking for a specific set of functionality? My goal with this project is to make a very simple JSON output, combining the xcresult test statuses and the code coverage from xccov. I just need them all in one simple file.

**Comment by bikee1235** [comment]
@davidahouse Seem good if we will get test information in JSON Format. 

I am using this XCTestHTMLReport that's very interactive.
